# Generated by Django 4.0 on 2022-06-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=1024)),
                ('programming_skills', models.CharField(max_length=1024)),
                ('industry_tools', models.CharField(max_length=1024)),
                ('office_tools', models.CharField(max_length=1024)),
                ('related_courses', models.CharField(max_length=1024)),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='info_api.account')),
            ],
        ),
    ]
