# Generated by Django 4.0 on 2022-06-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_api', '0003_alter_resume_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='*', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='account_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='info_api.account'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='account_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='info_api.account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='account_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='info_api.account'),
        ),
    ]
